spring.application.name=pokemon-project

spring.datasource.url=jdbc:mysql://localhost:3306/pokemon_proj
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

app.jwt.secret=346bf7d8bc7bdb51a3bcdc746e7830923f8b62cf19d8b7aaab2ec2cba35bc7e7
app.jwt.expiration-milliseconds=604800000
