spring.application.name=pokemon-project
spring.config.import=optional:file:.env[.properties]
spring.messages.encoding=UTF-8

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-milliseconds=${JWT_EXPIRY}

# PokeAPI Configuration
pokeapi.base-url=https://pokeapi.co/api/v2

# OpenApi Configuration
scalar.theme=kepler
scalar.dark-mode=true
scalar.hide-client-button=true

